//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MockScadaServerClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.multispeak.org/Version_4.1_Release", ConfigurationName="ServiceReference1.SCADA_ServerSoap")]
    public interface SCADA_ServerSoap {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SCADA_ServerSoapChannel : MockScadaServerClient.ServiceReference1.SCADA_ServerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SCADA_ServerSoapClient : System.ServiceModel.ClientBase<MockScadaServerClient.ServiceReference1.SCADA_ServerSoap>, MockScadaServerClient.ServiceReference1.SCADA_ServerSoap {
        
        public SCADA_ServerSoapClient() {
        }
        
        public SCADA_ServerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SCADA_ServerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCADA_ServerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SCADA_ServerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
    }
}
